import mongoose from "mongoose";
import Counter from "./counter";

export interface CodeModel extends mongoose.Document {
  id: number;
  contestId: number;
  teamId: number;
  name: string;
  content: string;
  language: string;
  compileInfo: string;
  createdAt: Date;
  createdBy: number;
  updatedAt: Date;
  updatedBy: number;
}

const codeSchema = new mongoose.Schema<CodeModel>(
  {
    id: { type: Number, unique: true }, // use auto-increment id, instead of _id generated by database
    contestId: { type: Number, required: true },
    teamId: { type: Number, required: true },
    name: { type: String, required: true },
    content: { type: String, required: true },
    language: { type: String, required: true },
    compileInfo: String,
    createdAt: { type: Date, default: Date.now },
    createdBy: Number,
    updatedAt: { type: Date, default: Date.now },
    updatedBy: Number
  },
  {
    collection: "codes"
  }
);

codeSchema.pre<CodeModel>("save", function(next) {
  Counter.findByIdAndUpdate(
    "code",
    { $inc: { count: 1 } },
    { new: true, upsert: true },
    (err, counter: any) => {
      if (err) {
        return next(err);
      }
      this.id = counter.count;
      next();
    }
  );
});

export default mongoose.model<CodeModel>("Code", codeSchema);
